"use client";

import EnhancedToolLayout from"@/components/EnhancedToolLayout";

export default function PlagiarismCheckerClient() {
  const promptTemplate = (input: string) => {
    return`You are an advanced AI detection algorithm and plagiarism expert. Your job is to analyze text for robotic patterns, repetitive structures, common AI buzzwords, and lack of human variance (perplexity/burstiness). Provide a harsh but accurate assessment of how likely the text is generated by AI, and give constructive feedback to humanize it.
    
Analyze the following text for signs of AI generation and potential plagiarism.
    
Text to analyze:"${input}"

Please provide your analysis in the following Markdown format:
## AI Detection Analysis
[Provide an estimated percentage of how much of this text appears to be AI-generated, e.g.,"Probability of AI generation: 85%"]

## Detailed Breakdown
[Identify specific robotic patterns, repetitive structures, or lack of"burstiness" and"perplexity" (common AI footprints)]

## Originality Assessment
[Mention if the concepts sound generic or highly derivative]

## Humanization Suggestions
[Provide 3-4 actionable tips on how the author can rewrite this text to make it sound more natural, human, and authentic]

Important: This is an estimate for educational improvement only — not a legal plagiarism verdict.`;
  };

  return (
    <EnhancedToolLayout
      toolSlug="plagiarism-checker"
      toolName="AI Writing Detector"
      placeholder="Paste your essay or article here to analyze for AI-like patterns..."
      promptTemplate={promptTemplate}
      systemPrompt="You analyze writing for AI-like patterns and generic phrasing. Be direct, structured, and constructive. Use Markdown headings. Never claim 100% certainty. Never present results as a legal plagiarism verdict or database match."
      options={[]}
    />
  );
}
